[default_session]
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~"
startup_command = "nvim ~/.config/dotfiles/.tmux.conf"
preview_command = "bat --color=always ~/.config/dotfiles/.tmux.conf"

[[session]]
name = "zshrc config"
path = "~"
startup_command = "nvim ~/.config/dotfiles/.zshrc"
preview_command = "bat --color=always ~/.zshrc"

[[session]]
name = "nvim config"
path = "~/.config/dotfiles/nvim"
startup_command = "nvim"

[[session]]
name = "config"
path = "~/.config/dotfiles"
startup_command = "nvim"

[[session]]
name = "hemea-main"
path = "~/Developer/travauxlib"
startup_command = "main"

[[session]]
name = "hemea-all"
path = "~/Developer/travauxlib"
startup_command = "all"

[[session]]
name = "hemea-shared"
path = "~/Developer/travauxlib"
startup_command = "shared"
